# v2 config — regime-routed, LLR-gated
paths:
  inputs_dir: "inputs"
  outputs_dir: "outputs"

symbols: ["BTCUSDT"]

data:
  months: ["2025-01","2025-02","2025-03","2025-04"]
  timezone: "UTC"

features:
  timeframe: "1m"
  windows: { macro: 60, micro: 15, slope_M: 60 }
  normalize: { zscore: true, percentiles: true }
  channels: [kappa_long, kappa_short, accel, slope_r2, atr_p, bbw_p, donch_w_p, donch_pos, body_frac, wick_bias, re_burst, trend_age]

cusum:
  enabled: true
  returns: "log"
  drift_k: [0.0, "q50_abs_r"]
  h_quantiles: [0.80, 0.85, 0.90]
  sigma_window: 60
  cooloff_bars: 40

regime:
  k: 8
  fingerprint: [atr_p, bbw_p, donch_w_p, kappa_long, accel, slope_r2, donch_pos, body_frac, wick_bias, cusum_rate]
  ctx_tau: 0.3
  ctx_sim:
    type: "cosine"   # "cosine" | "rbf"
    gamma: 1.0       # used only if type == "rbf"

candidates:
  compression:
    bbw_p_max: 0.70
    donch_w_p_max: 0.80
    atr_p_max: 0.30
  trigger:
    body_frac_min: 0.60
    accel_min: 1.5
    donch_pos_min_long: 0.80
    donch_pos_max_short: 0.20
  spacing_bars: 45
  require_cusum: true

label:
  use_tick_first_touch: true
  sl_mult: 20
  tp_mult: 60
  time_limit_bars: 2880
  slippage_bps: 3
  price_quantization: true

mining:
  horizons: [macro, micro]
  lengths:
    - {pre: 16, post: 32}
    - {pre: 32, post: 48}
  topk_per_class: 20
  eps_percentile: 15
  banks: [GOOD, BAD]

gating_search:
  eps_multiplier: [0.8, 0.9, 1.0, 1.1]
  K_hits: [1, 2, 3]
  lookback_L: [20, 30, 50]
  bad_margin: [0.0, 0.2, 0.5]
  breakout_buffer_atr: [0.0, 0.5, 1.0]
  ppv_prune: 0.6
  min_trades_per_month: 3
  max_dd_R: 8
  ridge_lambda: 1.0

risk:
  sl_mult: 20
  tp_mult: 60
  trailing: "off"

walkforward:
  train_months: 3
  test_months: 1
  step_months: 1
