# v2 config — regime-routed, LLR-gated
paths:
  inputs_dir: "inputs"
  outputs_dir: "outputs"

symbols: ["BTCUSDT"]

data:
  months: ["2025-01","2025-02","2025-03","2025-04"]
  timezone: "UTC"

features:
  timeframe: "1m"
  windows: { macro: 60, micro: 15, slope_M: 60 }
  normalize: { zscore: true, percentiles: true }
  channels: [kappa_long, kappa_short, accel, slope_r2, atr_p, bbw_p, donch_w_p, donch_pos, body_frac, wick_bias, re_burst, trend_age]

cusum:
  enabled: true
  returns: "log"
  drift_k: [0.0, "q50_abs_r"]
  h_quantiles: [0.80, 0.85, 0.90]
  sigma_window: 60
  cooloff_bars: 40

regime:
  k: 6           # fewer regimes increases per-regime data density
  min_len: 40    # keep as-is if already present
  fingerprint: [atr_p, bbw_p, donch_w_p, kappa_long, accel, slope_r2, donch_pos, body_frac, wick_bias, cusum_rate]
  ctx_tau: 0.3
  ctx_sim:
    type: "cosine"   # "cosine" | "rbf"
    gamma: 1.0       # used only if type == "rbf"

candidates:
  compression:
    bbw_p_max: 0.95        # was 0.70–0.85
    donch_w_p_max: 0.98    # was 0.80–0.90
    atr_p_max: 0.90        # was <= 0.60
  trigger:
    body_frac_min: 0.40    # was 0.50–0.60
    accel_min: 0.60        # was 1.0–1.5
    donch_pos_min_long: 0.60   # was 0.70–0.80
    donch_pos_max_short: 0.40  # was 0.20–0.30
  spacing_bars: 15         # was 30–45
  require_cusum: false     # remove the CUSUM requirement for now

label:
  use_tick_first_touch: true
  sl_mult: 20
  tp_mult: 60
  time_limit_bars: 2880
  slippage_bps: 3
  price_quantization: true

mining:
  horizons: [macro, micro]
  lengths:
    - {pre: 16, post: 32}
    - {pre: 32, post: 48}
  topk_per_class: 40      # was 20–30
  eps_percentile: 35      # was 15–25; looser distance → more matches
  ppv_prune: 0.30         # keep more GOOD motifs during pruning
  banks: [GOOD, BAD]

gating_search:
  eps_multiplier: [1.3, 1.4, 1.5]   # expand coverage at match-time
  K_hits: [1]                       # allow single strong GOOD hit
  bad_margin: [0.0]                 # disable Δ for bootstrap
  breakout_buffer_atr: [0.0]        # allow naked Donchian breakout
  min_trades_per_month: 1           # accept tiny coverage at start
  max_dd_R: 100                     # soft drawdown cap for now
  ridge_lambda: 0.25                # slightly looser regularization

risk:
  sl_mult: 20
  tp_mult: 60
  trailing: "off"

walkforward:
  train_months: 3
  test_months: 1
  step_months: 1
